name: Extension proposal
description: Propose a major change to the spec. Examples of extension proposal include [GTFS-Fares v2](https://gtfs.org/extensions/fares-v2/) or [GTFS-TripModifications](https://github.com/google/transit/issues/369).
labels: ['extension-proposal']

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a new extension proposal, please make sure there isn't an already [existing extension proposal](https://gtfs.org/extensions/).
  - type: textarea
    attributes:
      label: Describe the problem
      description: >
        Describe what you are trying to achieve, and how the spec is making it difficult.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use cases
      description: >
        Share examples of the scenarios you want the proposal to address, e.g GTFS-Fares v2 makes it possible to display the cost of a monthly pass.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: >
        A clear description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Additional information that can help the community better understand your need.
    validations:
      required: false
