name: Spec improvement
description: Propose an update to the existing spec, such as clarifying descriptions or adding new fields.
labels: ['improvement']

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a spec improvement, please make sure there isn't an already [existing issue](https://github.com/google/transit/issues?q=+is%3Aissue+label%3Aimprovement).
  - type: textarea
    attributes:
      label: Describe the problem
      description: >
        Describe what you are trying to achieve, and how the spec is making it difficult. Describe any other means you currently use to get the job done or to have the information you need.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use cases
      description: >
        Share examples of scenarios you want the improvement to address. [Here's a great example of communicating a complex use case](https://github.com/google/transit/pull/352#issuecomment-1284756181).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: >
        A clear description of what you want to happen that includes the GTFS files and fields affected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Additional information that can help the community better understand your need.
    validations:
      required: false
